#!/usr/bin/env ruby
require 'json'

FIXEDGAP = 0.02
class Array
  def analyze_block
    self.each do |line|
      if line[0] == "#"
        next
      else
        begin
          data = line.gsub("\n", '').split("\t")

          time = data.first.split
          time = time[0].to_f * 60 * 100 + time[1].to_f * 100 + time.last.to_i
          block_data = {
            time: (time / (FIXEDGAP * 100)).to_i,
            type: data[1].to_i,
            pointImg: data[2],
            top: data[3].to_f,
            left: data[4].to_f
          }
          yield block_data
        rescue
          next
        end
      end
    end
  end
end


lines = IO.readlines '1/easy.level'
easy_blocks = []
lines.analyze_block do |block|
  easy_blocks << block
end

level = {
  name: "The Letter",
  audio: "1-letter.mp3",
  previewAudio: "1-letter-p.mp3",
  sketch: "1-letter-sketch.jpg",
  blocks: easy_blocks
}

File.open('1/easy.json', 'w') do |file|
  file.write easy_blocks.to_json
end

File.open('1/level.json', 'w') do |file|
  file.write level.to_json
end